## System Architecture

```mermaid
graph TD
    User --> Query
    Query --> MainAgent

    MainAgent --> Guardrails
    MainAgent --> RAG
    MainAgent --> LLMHub

    RAG --> VectorDB

    LLMHub --> Eval
    Eval -->|ok| User
    Eval -->|not ok| MainAgent
```
